export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOADING_DATA = 'LOADING_DATA';
export const GET_EXERCISES = 'GET_EXERCISES';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';